spring:
  profiles:
    active: test

---
server:
  port: 8001

mybatis:
  type-aliases-package: com.example.springcloud.pojo
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

spring:
  profiles: dev
  application:
    name: springcloud-provider-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB_02?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xielibin20001011

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.cn:7001/eureka,http://eureka7002.cn:7002/eureka, http://eureka7003.cn:7003/eureka
  instance:
    instance-id: java-spring-cloud01

info:
  app.name: demo for Spring Cloud
  company.name: GPNU
---
server:
  port: 8001

mybatis:
  type-aliases-package: com.example.springcloud.pojo
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

spring:
  profiles: test
  application:
    name: springcloud-provider-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB_03?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xielibin20001011

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.cn:7001/eureka,http://eureka7002.cn:7002/eureka, http://eureka7003.cn:7003/eureka
  instance:
    instance-id: java-spring-cloud01

info:
  app.name: demo for Spring Cloud
  company.name: GPNU
