server:
  port: 8802
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:  #此处标志要绑定的rabbitmq信息
       defaultRabbit: #表示定义的名称，用于后续整合
        type: rabbit # 消息组件的类型
        environment:
          spring:
            rabbitmq:
              host: localhost
              port: 5672
              username: root
              password: 123456
      bindings:
        input: # 表示一个通道的名称
         destination: studyExchange #表示要使用的Exchange名称定义
         content-type: application/json #设置消息的类型，本次为json，如果是文本，则设置为“text/plain”
         binder: defaultRabbit
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.cn:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #心跳间隔
    lease-expiration-duration-in-seconds: 5 #超过5秒间隔会
    instance-id: consumer-8802.com #展示实例名称
    prefer-ip-address: true #访问路径为ip地址