# 配置端口号
server:
  port: 8080

# 配置消费者的名字
spring:
  application:
    name: springcloud-consumer-dept
  # 配置热部署的端口
  devtools:
    livereload:
      port: 32961

# Eureka配置
eureka:
  client:
    register-with-eureka: false # 不向Eureka中注册自己
    service-url:
      defaultZone: http://eureka7001.cn:7001/eureka,http://eureka7002.cn:7002/eureka, http://eureka7003.cn:7003/eureka

# 服务降级开启
feign:
  hystrix:
    enabled: true

# 与hystrix metrics stream配合使用
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  endpoint:
    hystrix:
      stream:
        enabled: true
