# 设置服务器启动的端口号
server:
  port: 8003

# 编写mybatis的有关配置
mybatis:
  type-aliases-package: com.example.springcloud.pojo
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

# 编写spring的有关配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB_03?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xielibin20001011

# 配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.cn:7001/eureka,http://eureka7002.cn:7002/eureka, http://eureka7003.cn:7003/eureka
  instance:
    instance-id: java-spring-cloud03
# 配置info
info:
  app.name: demo for Spring Cloud
  company.name: GPNU

