server:
  port: 3366

spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javalover-design/SpingCloud-Demo.git # 以http的方式连接
          skip-ssl-validation: true
        default-label: main
# rabbitmq配置连接信息
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123456
# 配置rabbitmq暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
eureka:
  client:
    service-url:
      defaultZone: http://localhost7001/eureka

